version: "3.1"
services:
  postgres:
    image: postgres
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dispatch
      POSTGRES_DB: dispatch
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: dispatch@netflix.com
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped
  web:
      env_file:
        - ./.env
      build: ../.
      command: ["server", "start", "dispatch.main:app", "--host=0.0.0.0"]
      ports:
        - "8000:8000"
  
volumes:
  postgres-data:
